[project]
name = "libpng"
version = "0.1.0"
type = "static"

[dependencies]
zlib = { url = "@Anglebase/zlib", version = "0.1.0" }

[generator."Visual Studio 17 2022"]
defines = ["_CRT_SECURE_NO_WARNINGS"]